# Generated by Django 3.2.8 on 2023-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('elo', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('creator_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.PositiveIntegerField()),
                ('player2_id', models.PositiveIntegerField()),
                ('winner_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
