# Generated by Django 3.2.8 on 2023-01-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_creator_id', to='base.user'),
        ),
        migrations.AlterField(
            model_name='results',
            name='player1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_player1_id', to='base.player'),
        ),
        migrations.AlterField(
            model_name='results',
            name='player2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_player2_id', to='base.player'),
        ),
        migrations.AlterField(
            model_name='results',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_winner_id', to='base.player'),
        ),
    ]
